# Site settings
title: Henry Blog
SEOTitle: 郑江的博客 | Henry Blog
email: 79095956@qq.com
url: "http://henryzj.github.io/blog/"              # your host, for absolute URL
baseurl: "/blog"                             # for example, '/blog' if your blog hosted on 'host/blog'